apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vuw8h0ouz-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vuw8h0ouz-nodejs 
  name: vuw8h0ouz-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: vuw8h0ouz-nodejs 
