apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vuw8h0ouz-nodejs 
  janus-idp.io/tekton: vuw8h0ouz-nodejs
  backstage.io/kubernetes-id: vuw8h0ouz-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vuw8h0ouz-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml